#### AUTO MODEL CLASS METHOD

####Using Transformer LLMs for Sentiment Analysis
* Here we don't need to mention explicitly for any class details

In [0]:
comment_1 = "I absolutely love this product. It works perfectly and exceeded my expectations"
comment_2 = "This service was very disappointing and a complete waste of money"
comment_3 = "The package arrived yesterday and was placed on the table"

Q1: Perform sentiment analysis on given customer comments.
1. Do not use pipeline function
2. Use Auto Classes
3. Apply distilbert-base-uncased-finetuned-sst-2-english model from huggingface hub

Step 1 - Create a tokenizer and prepare input tokens

In [0]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

2026-03-03 05:46:46.948557: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-03 05:46:46.959694: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-03 05:46:47.048193: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2026-03-03 05:46:47.086202: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1772516807.105220    2231 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1772516807.11

[2026-03-03 05:46:55,310] [WARNING] [real_accelerator.py:194:get_accelerator] Setting accelerator to CPU. If you have GPU or other accelerator, we were unable to detect it.
[2026-03-03 05:46:55,315] [INFO] [real_accelerator.py:239:get_accelerator] Setting ds_accelerator to cpu (auto detect)


/usr/bin/ld: cannot find -laio: No such file or directory
collect2: error: ld returned 1 exit status


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

##### In the above step, tokenizer class will be automatically chosen based on given model type

How to prepare the inputs using the tokenizer?

##### Below step is straight solution to perform all the pre processing stages in a single go

In [0]:
inputs = tokenizer([comment_1, comment_2, comment_3], padding=True, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[  101,  1045,  7078,  2293,  2023,  4031,  1012,  2009,  2573,  6669,
          1998, 14872,  2026, 10908,   102],
        [  101,  2023,  2326,  2001,  2200, 15640,  1998,  1037,  3143,  5949,
          1997,  2769,   102,     0,     0],
        [  101,  1996,  7427,  3369,  7483,  1998,  2001,  2872,  2006,  1996,
          2795,   102,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}


Step 2 - Create an use a model to generate raw outputs

In [0]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(checkpoint)
raw_outputs = model(inputs.input_ids, inputs.attention_mask)
print(raw_outputs)

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

SequenceClassifierOutput(loss=None, logits=tensor([[-4.3348,  4.7062],
        [ 4.7428, -3.8077],
        [-0.1458,  0.3013]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


Step 3 - Convert raw outputs to probabilities

In [0]:
import torch

predictions = torch.nn.functional.softmax(raw_outputs.logits, dim=1)
print(predictions)

tensor([[1.1844e-04, 9.9988e-01],
        [9.9981e-01, 1.9341e-04],
        [3.9007e-01, 6.0993e-01]], grad_fn=<SoftmaxBackward0>)


Step 4 - Format and display the results

In [0]:
    import pandas as pd

    pd_result_df = pd.DataFrame(predictions.tolist()) \
                        .rename({0: model.config.id2label[0].title(),
                                1: model.config.id2label[1].title()}, axis=1)

    pdf_comments = pd.DataFrame([comment_1, comment_2, comment_3], columns=['Comments']) 
    pd_final_result_df = pdf_comments.join(pd_result_df)
    display(pd_final_result_df)
    

Comments,Negative,Positive
I absolutely love this product. It works perfectly and exceeded my expectations,1.1843993706861511E-4,0.9998815059661865
This service was very disappointing and a complete waste of money,0.9998065829277039,1.9341372535564005E-4
The package arrived yesterday and was placed on the table,0.3900654911994934,0.6099345684051514


##### MODEL CLASS METHOD
* Here we need to explicitly mention the class details based on Model type

In [0]:
from transformers import DistilBertTokenizer
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = DistilBertTokenizer.from_pretrained(checkpoint)

In [0]:
## HERE WE IMPORTED THE DISTIL BERT MODEL TOKENIZER

In [0]:
inputs = tokenizer([comment_1, comment_2, comment_3], padding=True, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[  101,  1045,  7078,  2293,  2023,  4031,  1012,  2009,  2573,  6669,
          1998, 14872,  2026, 10908,   102],
        [  101,  2023,  2326,  2001,  2200, 15640,  1998,  1037,  3143,  5949,
          1997,  2769,   102,     0,     0],
        [  101,  1996,  7427,  3369,  7483,  1998,  2001,  2872,  2006,  1996,
          2795,   102,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}


In [0]:
from transformers import DistilBertForSequenceClassification
model = DistilBertForSequenceClassification.from_pretrained(checkpoint)
outputs = model(inputs.input_ids, inputs.attention_mask)
print(outputs)

SequenceClassifierOutput(loss=None, logits=tensor([[-4.3348,  4.7062],
        [ 4.7428, -3.8077],
        [-0.1458,  0.3013]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


In [0]:
import torch
predictions = torch.nn.functional.softmax(outputs.logits, dim=1) #apply to each row
print(predictions)

tensor([[1.1844e-04, 9.9988e-01],
        [9.9981e-01, 1.9341e-04],
        [3.9007e-01, 6.0993e-01]], grad_fn=<SoftmaxBackward0>)


In [0]:
import pandas as pd
pdf_results = pd.DataFrame(predictions.tolist()) \
                .rename({0: model.config.id2label[0].title(), 
                         1: model.config.id2label[1].title()}, 
                        axis=1)
pdf_comments = pd.DataFrame([comment_1, comment_2, comment_3], columns=['Comment']) 
pd_result_df = pdf_comments.join(pdf_results)
display(pd_result_df)               

Comment,Negative,Positive
I absolutely love this product. It works perfectly and exceeded my expectations,1.1843993706861511E-4,0.9998815059661865
This service was very disappointing and a complete waste of money,0.9998065829277039,1.9341372535564005E-4
The package arrived yesterday and was placed on the table,0.3900654911994934,0.6099345684051514


## USING PIPELINE OBJECT TO HANDLE THE PRE PROCESSING STAGES

Step 1 - Create the pipeline

In [0]:
from transformers import pipeline
classifier = pipeline(task="sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")


Device set to use cpu


#### STRAIGHT A WAY TO ACCESS THE MODEL AND ASKING THE QUESTIONS

In [0]:
results = classifier([comment_1, comment_2, comment_3])
print(results)

#### PIPELINE OBJECT HELPS US TO BUILD PRE PROCESSING STAGE

Step 2 - Extract a tokenizer and prepare input tokens

In [0]:
tokenizer = classifier.tokenizer
inputs = tokenizer([comment_1, comment_2, comment_3], padding=True, return_tensors="pt")
print(inputs)

{'input_ids': tensor([[  101,  1045,  7078,  2293,  2023,  4031,  1012,  2009,  2573,  6669,
          1998, 14872,  2026, 10908,   102],
        [  101,  2023,  2326,  2001,  2200, 15640,  1998,  1037,  3143,  5949,
          1997,  2769,   102,     0,     0],
        [  101,  1996,  7427,  3369,  7483,  1998,  2001,  2872,  2006,  1996,
          2795,   102,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]])}


Step 3 - Extract your model from the pipeline

In [0]:
model = classifier.model
outputs = model(inputs.input_ids, inputs.attention_mask)
print(outputs)

SequenceClassifierOutput(loss=None, logits=tensor([[-4.3348,  4.7062],
        [ 4.7428, -3.8077],
        [-0.1458,  0.3013]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)


Step 4 - Convert raw outputs to probabilities

In [0]:
import torch
predictions = torch.nn.functional.softmax(outputs.logits, dim=1) #apply to each row
print(predictions)

tensor([[1.1844e-04, 9.9988e-01],
        [9.9981e-01, 1.9341e-04],
        [3.9007e-01, 6.0993e-01]], grad_fn=<SoftmaxBackward0>)


Step 5 - Format and display the results

In [0]:
import pandas as pd
pdf_results = pd.DataFrame(predictions.tolist()) \
                .rename({0: model.config.id2label[0].title(), 
                         1: model.config.id2label[1].title()}, 
                        axis=1)
pdf_comments = pd.DataFrame([comment_1, comment_2, comment_3], columns=['Comment']) 
pd_result_df = pdf_comments.join(pdf_results)
display(pd_result_df)               

Comment,Negative,Positive
I absolutely love this product. It works perfectly and exceeded my expectations,1.1843993706861511E-4,0.9998815059661865
This service was very disappointing and a complete waste of money,0.9998065829277039,1.9341372535564005E-4
The package arrived yesterday and was placed on the table,0.3900654911994934,0.6099345684051514
